### ISSUE TITLE
Text font colour not being used in reading view.

### ISSUE THREAD

**Issue by MagePrometheus** [rien7/obsidian-colorful-tag#3]
version 1.0.1 windows 10 Obsidian 1.0 Theme minimal

The text colour as set in the plugin settings is fine in edit/live preview but remains the default in reading view.
I was using this CSS in a snippet and turned it off when I installed the plugin. It's a lot easier to set up than copy/paste this block for every single tag. Don't know if this ABC tag with a cherry CSS helps at all.

```css
/* Common to tags in all modes
   .cm-hashtag for reading
   .tag[href="#abc"] for edit/live */
   .cm-hashtag {
	font-size: 14px !important;
}
   
/* *** Specific tag #abc *** */
/* All modes
   .cm-hashtag-end.cm-tag-abc for reading
   .tag[href="#abc"] for edit/live */
.cm-hashtag-end.cm-tag-abc, .cm-hashtag-begin.cm-tag-abc,
.tag[href="#abc"] {
	font-size: 14px !important;
	color: rgb(232, 230, 227) !important;
	background-color: rgb(165, 29, 42) !important;
}
/* Only in edit/live modes # styling* (left end) */
.cm-hashtag-begin.cm-tag-abc {
	padding-top: 2px !important;
	padding-left: 5px !important;
}
/* Only edit/live modes tag name styling (right end) */
.cm-hashtag-end.cm-tag-abc {
	padding-top: 2px !important;
	padding-right: 10px !important;
}
/* All modes. emoji before # */
.cm-hashtag-begin.cm-tag-abc:before,
.tag[href="#abc"]:before {
	content: "🌱 ";
}
/* ****************************** */
```
